<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DonarumaAPI_DTOs\DonarumaAPI_DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AuthorizationPolices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

</Project>
